apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: namespace
  - name: service-name
  - name: service-port
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: len(result) == 0 || result[0] >= 0.99
    failureLimit: 0
    provider:
      prometheus:
        address: http://prometheus-server.prometheus
        query: >+
          sum(rate(
            nginx_gateway_fabric_upstream_server_responses{upstream="{{args.namespace}}_{{args.service-name}}_{{args.service-port}}", 
            code!~"[4-5].*"}[1m])
          ) by (upstream)
          /
          sum(rate(
            nginx_gateway_fabric_upstream_server_responses{upstream="{{args.namespace}}_{{args.service-name}}_{{args.service-port}}"}[1m])
          ) by (upstream)
          unless sum(rate(
            nginx_gateway_fabric_upstream_server_responses{upstream="{{args.namespace}}_{{args.service-name}}_{{args.service-port}}"}[1m])
          ) by (upstream) == 0
